# Generated by Django 4.2.16 on 2024-09-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20191115_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_morrisons',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='total_sainsburys',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='total_tesco',
        ),
        migrations.AddField(
            model_name='basket',
            name='total_amazon',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='basket',
            name='total_flipkart',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='basket',
            name='total_jio_mart',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product_total',
            field=models.IntegerField(default=1),
        ),
    ]
