# Generated by Django 4.2.16 on 2024-09-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_remove_basket_total_morrisons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_amazon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_flipkart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_jio_mart',
            field=models.IntegerField(default=0),
        ),
    ]
