# Generated by Django 4.2.16 on 2024-09-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_alter_basket_total_amazon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='total_jio_mart',
            new_name='total_jiomart',
        ),
    ]
