# Generated by Django 4.2.16 on 2024-09-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191114_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url_morrisons',
            new_name='url_amazon',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_sainsburys',
            new_name='url_flipkart',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_tesco',
            new_name='url_jiomart',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_morrisons',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_sainsburys',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_tesco',
        ),
        migrations.AddField(
            model_name='product',
            name='price_amazon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_flipkart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_jiomart',
            field=models.IntegerField(default=0),
        ),
    ]
