# Generated by Django 2.1.7 on 2025-12-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_url_morrisons_product_url_amazon_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
    ]
